server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/School
    username: root
    password: rtyuehe
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MariaDB10Dialect
        hbm2ddl:
          auto: update
